baseURL = "https://ycanales.github.io/"
defaultContentLanguage = "es"
languageCode = "es-cl"
title = "ycanales"
theme = "ananke"
googleAnalytics = "UA-120059612-1"

[languages]
  [languages.es]
    weight = 1
    languageName = "Español"
  [languages.en]
    weight = 2
    languageName = "English"
